IBX-6211: Added product edit route to EDIT_VIEWS const
ibexa/content-forms pull request #43
Opened 2023-07-20 16:49 UTC by mateuszdebinski

Jira: https://issues.ibexa.co/browse/IBX-6211

2023-07-21 06:07 UTC, konradoboza reviewed
Overall looks good, but can you double-check if CI fail is related?

2023-07-21 07:23 UTC, webhdx approved these changes

2023-07-21 07:30 UTC, mateuszdebinski commented
@konradoboza The error is independent of the PR, but I push a fix

2023-07-21 07:31 UTC, konradoboza approved these changes

2023-07-21 07:44 UTC, konradoboza commented
Summoning @mnocon to look if the Behat-related changes are ok. ;)

2023-07-21 10:15 UTC, mnocon approved these changes
+1 for Behat changes, thanks for taking care of it! 💪

2023-07-24 13:09 UTC, adamwojs requested changes

2023-07-24 13:09 UTC, adamwojs commented on src/lib/Form/Type/FieldType/DateFieldType.php
> +        'ibexa.product_catalog.product.edit',
ibexa/content-forms shouldn't refer to symbols defined in ibexa/product-catalog.

2023-07-24 14:21 UTC, closed without merging